name: Keep Supabase Alive

# Workflow to prevent Supabase from auto-pausing
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering

env:
  SUPABASE_ANON_KEY: ${{ vars.SUPABASE_ANON_KEY }}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://kqmngttdxhcvchqgwnvi.supabase.co/rest/v1/" \
          -H "apikey: ${{ env.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ env.SUPABASE_ANON_KEY }}"
